import { formatDateTime } from '@/utils/date'
import type { ReportHeader } from '@/@types/reports/SalesJournal'

interface ReportHeaderBlockProps {
    title: string
    period: string
    header: ReportHeader
}

/**
 * Taxpayer, software and "generated by" block printed above system-generated books (RMC 5-2021 Annex B).
 * Shown on screen and on the printout.
 */
export default function ReportHeaderBlock({ title, period, header }: ReportHeaderBlockProps) {
    return (
        <div className="mb-4 flex flex-col gap-4 border-b border-gray-200 pb-4 sm:flex-row sm:justify-between dark:border-gray-700 print:flex-row">
            <div className="min-w-0">
                <div className="text-xs font-bold tracking-wider text-gray-500 uppercase">{title}</div>
                <div className="mt-1 text-lg font-bold text-gray-900 dark:text-gray-100">{header.registeredName}</div>
                {header.businessName && <div className="text-gray-700 dark:text-gray-200">{header.businessName}</div>}
                <div className="text-gray-600 dark:text-gray-300">{header.address}</div>
                <div className="text-gray-600 dark:text-gray-300">
                    {header.vatRegistration} TIN: {header.tin}
                </div>
                <div className="mt-1 font-semibold text-gray-800 dark:text-gray-100">{period}</div>
            </div>
            <div className="shrink-0 text-sm text-gray-500 sm:text-right print:text-right">
                <div>
                    Software: {header.softwareName} v{header.softwareVersion}
                </div>
                <div>Generated by {header.generatedBy}</div>
                <div>on {formatDateTime(header.generatedAt)}</div>
            </div>
        </div>
    )
}
