import 'server-only'

import { z } from 'zod'
import { apiAuthHandler } from '@/server/routes/api'
import { getFileResponse, getJsonResponse } from '@/server/utils/response'
import { getSalesJournal } from '@/server/data/reports'
import { logAuditEvent } from '@/server/data/audit'
import { ACTION_REPORT_VIEW } from '@/constants/actions.constant'
import { DOCUMENT_TYPE_LABELS } from '@/constants/bir.constant'
import { DataError } from '@/@types/errors'
import { toCsv } from '@/utils/csv'
import { formatDateTime } from '@/utils/date'
import type { SalesJournal } from '@/@types/reports/SalesJournal'

const QuerySchema = z.object({
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    branchId: z.string().uuid().optional(),
    format: z.enum(['json', 'csv']).default('json'),
})

/** Every system-generated book shows the taxpayer, software and who generated it (RMC 5-2021 Annex B). */
const toSalesJournalCsv = (journal: SalesJournal) =>
    toCsv(
        [
            'Date',
            'Document No.',
            'Document Type',
            'Branch',
            'Customer TIN',
            'Customer Name',
            'Customer Address',
            'Description',
            'Gross Amount',
            'Discount',
            'VATable Sales',
            'Output VAT',
            'Zero-Rated Sales',
            'VAT-Exempt Sales',
            'Non-VAT Sales',
            'Total Amount',
        ],
        [
            ...journal.rows.map((row) => [
                row.invoiceDate,
                row.invoiceNumber,
                DOCUMENT_TYPE_LABELS[row.documentType],
                row.branchCode,
                row.buyerTin,
                row.buyerName,
                row.buyerAddress,
                row.description,
                row.grossAmount,
                row.discountAmount,
                row.vatableSales,
                row.vatAmount,
                row.zeroRatedSales,
                row.vatExemptSales,
                row.nonVatSales,
                row.totalAmount,
            ]),
            [
                'TOTAL',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                journal.totals.grossAmount,
                journal.totals.discountAmount,
                journal.totals.vatableSales,
                journal.totals.vatAmount,
                journal.totals.zeroRatedSales,
                journal.totals.vatExemptSales,
                journal.totals.nonVatSales,
                journal.totals.totalAmount,
            ],
        ],
        [
            ['SALES JOURNAL'],
            [journal.header.registeredName],
            ...(journal.header.businessName ? [[journal.header.businessName]] : []),
            [journal.header.address],
            [`${journal.header.vatRegistration} TIN: ${journal.header.tin}`],
            [`Period: ${journal.from} to ${journal.to}`],
            [`Software: ${journal.header.softwareName} v${journal.header.softwareVersion}`],
            [`Generated by ${journal.header.generatedBy} on ${formatDateTime(journal.header.generatedAt)}`],
        ],
    )

export const GET = apiAuthHandler(
    async (req, _ctx, { supabase, organizationId, user }) => {
        const parsed = QuerySchema.safeParse(Object.fromEntries(new URL(req.url).searchParams))
        if (!parsed.success) throw new DataError('Choose a valid date range.')
        const { from, to, branchId, format } = parsed.data
        if (from > to) throw new DataError('The start date must be before the end date.')

        const journal = await getSalesJournal(supabase, organizationId, user, { from, to, branchId })
        if (format === 'csv') {
            await logAuditEvent(supabase, organizationId, {
                action: 'export',
                entityType: 'reports',
                summary: `Exported Sales Journal ${from} to ${to}`,
            })
            return getFileResponse(`﻿${toSalesJournalCsv(journal)}`, `sales-journal_${from}_${to}.csv`, 'text/csv')
        }
        return getJsonResponse(journal)
    },
    { action: ACTION_REPORT_VIEW },
)
