import 'server-only'

import { z } from 'zod'
import { apiAuthHandler } from '@/server/routes/api'
import { getFileResponse, getJsonResponse } from '@/server/utils/response'
import { getSummaryListOfSales } from '@/server/data/reports'
import { logAuditEvent } from '@/server/data/audit'
import { ACTION_REPORT_VIEW } from '@/constants/actions.constant'
import { DataError } from '@/@types/errors'
import { toCsv } from '@/utils/csv'
import { formatDateTime } from '@/utils/date'
import type { SummaryListOfSales } from '@/@types/reports/SummaryListOfSales'

const QuerySchema = z.object({
    year: z.coerce.number().int().min(2000).max(2100),
    quarter: z.coerce.number().int().min(1).max(4),
    format: z.enum(['json', 'csv']).default('json'),
})

const toSlsCsv = (report: SummaryListOfSales) =>
    toCsv(
        [
            'TIN',
            'Registered Name',
            'Address',
            'Gross Sales',
            'Exempt Sales',
            'Zero-Rated Sales',
            'Taxable Sales',
            'Output Tax',
            'Gross Taxable Sales',
        ],
        [
            ...report.rows.map((row) => [
                row.buyerTin,
                row.buyerName,
                row.buyerAddress,
                row.grossSales,
                row.exemptSales,
                row.zeroRatedSales,
                row.taxableSales,
                row.outputTax,
                row.grossTaxableSales,
            ]),
            [
                'TOTAL',
                '',
                '',
                report.totals.grossSales,
                report.totals.exemptSales,
                report.totals.zeroRatedSales,
                report.totals.taxableSales,
                report.totals.outputTax,
                report.totals.grossTaxableSales,
            ],
        ],
        [
            ['SUMMARY LIST OF SALES'],
            [report.header.registeredName],
            [report.header.address],
            [`${report.header.vatRegistration} TIN: ${report.header.tin}`],
            [`Quarter ${report.quarter}, ${report.year}`],
            [`Software: ${report.header.softwareName} v${report.header.softwareVersion}`],
            [`Generated by ${report.header.generatedBy} on ${formatDateTime(report.header.generatedAt)}`],
        ],
    )

export const GET = apiAuthHandler(
    async (req, _ctx, { supabase, organizationId, user }) => {
        const parsed = QuerySchema.safeParse(Object.fromEntries(new URL(req.url).searchParams))
        if (!parsed.success) throw new DataError('Choose a valid year and quarter.')
        const { year, format } = parsed.data
        const quarter = parsed.data.quarter as 1 | 2 | 3 | 4

        const report = await getSummaryListOfSales(supabase, organizationId, user, { year, quarter })
        if (format === 'csv') {
            await logAuditEvent(supabase, organizationId, {
                action: 'export',
                entityType: 'reports',
                summary: `Exported Summary List of Sales Q${quarter} ${year}`,
            })
            return getFileResponse(`﻿${toSlsCsv(report)}`, `summary-list-of-sales_${year}-Q${quarter}.csv`, 'text/csv')
        }
        return getJsonResponse(report)
    },
    { action: ACTION_REPORT_VIEW },
)
